# Generated by Django 2.1.4 on 2019-01-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190103_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='items', to='api.Detail'),
        ),
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='lists', through='api.ListInventory', to='api.Item'),
        ),
        migrations.AlterField(
            model_name='location',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='locations', through='api.LocationInventory', to='api.Item'),
        ),
    ]
