# Generated by Django 2.1.7 on 2019-03-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190103_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
