# Generated by Django 2.1.4 on 2019-01-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190101_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='mode',
        ),
    ]
