# Generated by Django 2.1.4 on 2019-01-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190101_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'acquired'), (2, 'removed'), (3, 'lost'), (4, 'recorded')]),
        ),
    ]
